slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    map_update_interval: 1.0
    minimum_time_interval: 0.1

    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.1
    
    solve_frequency: 0.5
    transform_publish_period: 0.05
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan_filtered
    mode: mapping
    resolution: 0.025
    max_laser_range: 1.0
    use_sim_time: false
    occupancy_threshold: 0.1
    min_pass_through: 2
